<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-24T11:45:42 IST" name="Default suite" finished-at="2024-03-24T11:46:04 IST" duration-ms="22384">
    <groups>
      <group name="RegressionSuite">
        <method signature="CreateOrgTest.createOrgTest()[pri:0, instance:orgTestCases.CreateOrgTest@7f0eb4b4]" name="createOrgTest" class="orgTestCases.CreateOrgTest"/>
      </group> <!-- RegressionSuite -->
      <group name="SmokeSuite">
        <method signature="CreateOrgTest.createOrgTest()[pri:0, instance:orgTestCases.CreateOrgTest@7f0eb4b4]" name="createOrgTest" class="orgTestCases.CreateOrgTest"/>
      </group> <!-- SmokeSuite -->
    </groups>
    <test started-at="2024-03-24T11:45:42 IST" name="Default test" finished-at="2024-03-24T11:46:04 IST" duration-ms="22384">
      <class name="orgTestCases.CreateOrgTest">
        <test-method is-config="true" signature="bcConfig()[pri:0, instance:orgTestCases.CreateOrgTest@7f0eb4b4]" started-at="2024-03-24T11:45:42 IST" name="bcConfig" finished-at="2024-03-24T11:45:45 IST" duration-ms="3082" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bcConfig -->
        <test-method is-config="true" signature="bmConfig()[pri:0, instance:orgTestCases.CreateOrgTest@7f0eb4b4]" started-at="2024-03-24T11:45:45 IST" name="bmConfig" finished-at="2024-03-24T11:45:47 IST" duration-ms="2562" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bmConfig -->
        <test-method signature="createOrgTest()[pri:0, instance:orgTestCases.CreateOrgTest@7f0eb4b4]" started-at="2024-03-24T11:45:47 IST" name="createOrgTest" finished-at="2024-03-24T11:45:59 IST" duration-ms="12092" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at orgTestCases.CreateOrgTest.createOrgTest(CreateOrgTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrgTest -->
        <test-method is-config="true" signature="afConfig()[pri:0, instance:orgTestCases.CreateOrgTest@7f0eb4b4]" started-at="2024-03-24T11:45:59 IST" name="afConfig" finished-at="2024-03-24T11:46:04 IST" duration-ms="4598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afConfig -->
        <test-method is-config="true" signature="acConfig()[pri:0, instance:orgTestCases.CreateOrgTest@7f0eb4b4]" started-at="2024-03-24T11:46:04 IST" name="acConfig" finished-at="2024-03-24T11:46:04 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- acConfig -->
      </class> <!-- orgTestCases.CreateOrgTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
